In [1]:
data = """
Digital Wallets (E-wallets): Highly popular for quick, one-click checkout via smartphones, such as Apple Pay, Google Pay, and PayPal.
Credit & Debit Cards: The foundation of modern e-commerce (Visa, Mastercard, American Express), offering immediate payment authorization.
Buy Now, Pay Later (BNPL): Short-term financing options that allow customers to pay in installments (e.g., Klarna, Affirm, Afterpay), which can increase conversion rates.
Bank Transfers / ACH: Direct transfers from a customer's bank account, often with lower processing fees (e.g., SEPA in Europe, ACH in the US).
Cryptocurrency: Digital currencies like Bitcoin or Ethereum used for secure, often cross-border transactions.
Cash on Delivery (COD): Payment made by cash or card upon receiving the product, common in specific regions.
"""

lines = data.splitlines()

methods = []
for line in lines:
    if line != '':
        payment_method = line.split(':')[0]  # Extract the payment method name
        methods.append(payment_method)
        # print(f"Payment Method: {payment_method}")

In [1]:
import random
import ipaddress
import pandas as pd
from faker import Faker
import numpy as np
import json

In [ ]:
random.sample([1, 5],k=2)

[1, 5]

In [92]:
int(np.random.choice([1, 5], p=[0.8, 0.2], replace=False))

1

In [93]:
x = [274.85, 50.29, 698.76, 409.00, 247.18]

In [94]:
sum(x)

1680.0800000000002

In [2]:
'payment_methods'.upper()

'PAYMENT_METHODS'

In [ ]:
fake = Faker()

In [65]:
print(fake.unique.email())
print(fake.unique.user_name())
print(fake.unique.name())

bbarrett@example.com
webbbrian
Derrick Vasquez

In [6]:
STATES = ['landing_page', 'search', 'category_view', 'product_view', 
         'variant_selected', 'add_to_cart', 'cart_view', 'remove_from_cart', 'checkout_started', 
         'login_required', 'shipping_info', 'payment_info', 'payment_failed', 'purchase_completed',
         'wishlist', 'exit']

In [7]:
len(STATES)

16

In [2]:
df = pd.read_clipboard(sep='|')

In [4]:

df_01 = df.iloc[1:, 1:-1].copy()
df_01.columns = df_01.columns.str.strip()
df_01.index = df_01['From / To'].values
df_02 = df_01.iloc[:, 1:].copy()
df_03 = df_02.map(lambda x: float(x))
df_03.index = df_03.index.str.lower().str.strip()
# df_03.apply(lambda x:np.asarray(x), axis=1).to_json('matrix_transition.json', orient='index', indent=4)

In [10]:
df_03

,Landing,Search,Category,Product,Variant,Add Cart,Cart,Remove,Checkout,Login,Shipping,Payment,Pay Failed,Purchase,Wishlist,Exit
start,1.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
landing_page,0.0,0.2,0.25,0.15,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.40
search,0.0,0.1,0.15,0.50,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.25
category_view,0.0,0.1,0.05,0.55,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.30
product_view,0.0,0.0,0.10,0.05,0.25,0.15,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.10,0.35
variant_selected,0.0,0.0,0.00,0.15,0.05,0.60,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.20
add_to_cart,0.0,0.0,0.00,0.20,0.00,0.05,0.60,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.15
cart_view,0.0,0.0,0.00,0.10,0.00,0.00,0.05,0.1,0.45,0.00,0.00,0.00,0.00,0.00,0.00,0.30
remove_from_cart,0.0,0.0,0.00,0.30,0.00,0.20,0.30,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.20
checkout_started,0.0,0.0,0.00,0.00,0.00,0.00,0.10,0.0,0.05,0.20,0.45,0.00,0.00,0.00,0.00,0.20
login_required,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.05,0.70,0.00,0.00,0.00,0.00,0.25
shipping_info,0.0,0.0,0.00,0.00,0.00,0.00,0.10,0.0,0.00,0.00,0.05,0.65,0.00,0.00,0.00,0.20
payment_info,0.0,0.0,0.00,0.00,0.00,0.00,0.05,0.0,0.00,0.00,0.00,0.05,0.15,0.65,0.00,0.10
payment_failed,0.0,0.0,0.00,0.00,0.00,0.00,0.15,0.0,0.00,0.00,0.00,0.55,0.05,0.00,0.00,0.25
purchase_completed,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,1.00,0.00,0.00
wishlist,0.0,0.0,0.00,0.50,0.00,0.20,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.05,0.25
exit,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00

In [9]:
df_03.apply(lambda x:np.asarray(x), axis=1).to_json('matrix_transition.json', orient='index', indent=4)

In [29]:
df_03 = pd.read_clipboard(sep='\t')

In [30]:
df_04 = df_03.set_index('INDEX')
df_04.apply(lambda x:np.asarray(x), axis=1).to_json('matrix_transition.json', orient='index', indent=4)

In [40]:
e = {"a":10, "b":60, "c":['10', 9]}

In [42]:
e.pop('a')

10

In [44]:
w = {1, 9, 6}

In [46]:
w.discard(9)

In [48]:
x = [50*12*0.45, 3*4*3]

In [50]:
sum(x)

306.0

In [28]:
json.dumps(e)

'[{"data": {"a": 10, "b": 60, "c": ["10", 9]}}]'

In [33]:
df = pd.read_csv(r"C:\Users\dante\ecommerce_rest_api\app\products.csv")
df

,name,description,price,category,image_url,stock_quantity,is_available
0,Cocina de Pie Mabe CMP6014AG0 4 Quemadores Gra...,No aplica para retiro en tienda. Sólo delivery...,679.00,Electrohogar,https://www.metro.pe/cocina-de-pie-mabe-cmp601...,22,True
1,Refrigerador Indurama 177L RI-289D Autofrost C...,No aplica para retiro en tienda. Sólo delivery...,899.00,Electrohogar,https://www.metro.pe/refrigerador-indurama-177...,40,True
2,Refrigeradora Hisense Top Mount 205L RD267H De...,No aplica para retiro en tienda. Sólo delivery...,0.00,Electrohogar,https://www.metro.pe/refrigeradora-hisense-top...,25,True
3,Lavadora Hisense Carga Superior 10KG WT3J1023UT,No aplica para retiro en tienda. Sólo delivery...,699.00,Electrohogar,https://www.metro.pe/lavadora-hisense-carga-su...,37,True
4,Refrigeradora Indurama Ri-359I No Frost 2 Puertas,No aplica para retiro en tienda. Sólo delivery...,1099.00,Electrohogar,https://www.metro.pe/refrigeradora-indurama-ri...,4,True
...,...,...,...,...,...,...,...
459,Bestway Colchón Inflable 1 Plaza + Almohada + ...,- Tamaño: 1 plazaIncluye:- Colchón inflable de...,49.90,Deportes y Outdoors,https://www.metro.pe/bestway-colchon-inflable-...,7,True
460,Sombrilla 180cm Outzen Blanca,- Material: Poliéster / Acero - Factor de Prot...,23.97,Deportes y Outdoors,https://www.metro.pe/sombrilla-180cm-outzen-bl...,27,True
461,Quitasol Outzen 2mt Caño Calipso,Dimensiones: 2mtMaterial: PoliésterComodidad y...,20.97,Deportes y Outdoors,https://www.metro.pe/quitasol-outzen-2mt-ca-o-...,32,True
462,Flotador Inflable para Brazos Bestway Disney P...,Edad recomendada: De 5 a 12 añosFlotador infla...,4.50,Deportes y Outdoors,https://www.metro.pe/flotador-inflable-para-br...,7,True
463,Piscina para Niños Bestway Fresita 160cm,No aplica para retiro en tienda. Sólo delivery...,49.90,Deportes y Outdoors,https://www.metro.pe/piscina-para-ninos-bestwa...,32,True

In [37]:
list(df.is_available.unique())

[np.True_]

In [57]:
for item in df.itertuples(index=False):
    assert isinstance(item.stock_quantity, (int, float)), f"Stock quantity for {item.name} is not a number: {item.stock_quantity}"
    print(item.stock_quantity)
    print(item.stock_quantity)

22
22
40
40
25
25
37
37
4
4
41
41
32
32
29
29
7
7
16
16
25
25
2
2
17
17
35
35
40
40
12
12
31
31
9
9
35
35
1
1
3
3
32
32
28
28
28
28
2
2
21
21
30
30
6
6
32
32
44
44
46
46
41
41
16
16
18
18
35
35
40
40
29
29
4
4
48
48
5
5
18
18
11
11
5
5
2
2
31
31
12
12
34
34
7
7
46
46
5
5
12
12
32
32
14
14
1
1
38
38
6
6
13
13
38
38
8
8
9
9
25
25
43
43
33
33
32
32
16
16
10
10
39
39
22
22
7
7
35
35
9
9
31
31
40
40
13
13
35
35
19
19
39
39
7
7
14
14
36
36
20
20
12
12
18
18
23
23
28
28
36
36
29
29
46
46
7
7
11
11
5
5
30
30
25
25
2
2
17
17
10
10
47
47
34
34
27
27
32
32
3
3
8
8
39
39
32
32
16
16
35
35
23
23
9
9
1
1
13
13
22
22
33
33
38
38
24
24
19
19
1
1
21
21
5
5
34
34
29
29
17
17
13
13
10
10
2
2
11
11
20
20
32
32
27
27
39
39
26
26
41
41
9
9
24
24
9
9
14
14
27
27
17
17
18
18
46
46
26
26
30
30
14
14
22
22
33
33
46
46
24
24
41
41
26
26
36
36
8
8
18
18
37
37
3
3
22
22
15
15
36
36
31
31
31
31
20
20
16
16
38
38
2
2
48
48
47
47
10
10
9
9
49
49
40
40
30
30
26
26
17
17
45
45
23
23
11
11
40
40
24
24
46
46
3
3
42
42
5
5
42
42
49
49
11
11
5
5
12
12
11
11
29
29
40
40
34
34
41
41
25
25
44
44
47
47
45
45
38
38
16
16
47
47
8
8
46
46
27
27
3
3
47
47
44
44
46
46
30
30
45
45
28
28
3
3
38
38
3
3
15
15
27
27
1
1
24
24
5
5
49
49
7
7
31
31
2
2
3
3
16
16
7
7
26
26
10
10
35
35
44
44
33
33
7
7
37
37
25
25
12
12
17
17
18
18
45
45
6
6
45
45
10
10
37
37
10
10
19
19
49
49
7
7
21
21
17
17
24
24
13
13
14
14
45
45
22
22
39
39
7
7
33
33
38
38
36
36
42
42
28
28
20
20
47
47
21
21
35
35
23
23
16
16
46
46
20
20
28
28
28
28
13
13
19
19
4
4
25
25
43
43
22
22
32
32
3
3
24
24
29
29
45
45
7
7
4
4
11
11
21
21
32
32
8
8
35
35
39
39
7
7
47
47
1
1
19
19
44
44
18
18
28
28
11
11
49
49
9
9
17
17
21
21
39
39
41
41
20
20
15
15
49
49
12
12
32
32
24
24
10
10
17
17
45
45
36
36
26
26
15
15
14
14
42
42
41
41
26
26
14
14
36
36
16
16
35
35
32
32
24
24
43
43
44
44
39
39
6
6
45
45
18
18
27
27
17
17
14
14
43
43
21
21
13
13
16
16
20
20
42
42
27
27
31
31
13
13
10
10
43
43
15
15
28
28
6
6
7
7
41
41
39
39
10
10
15
15
7
7
19
19
4
4
35
35
36
36
19
19
2
2
18
18
49
49
8
8
3
3
48
48
13
13
31
31
35
35
28
28
22
22
3
3
27
27
25
25
38
38
16
16
30
30
8
8
49
49
34
34
27
27
13
13
3
3
22
22
3
3
14
14
30
30
8
8
34
34
21
21
28
28
43
43
34
34
34
34
46
46
8
8
28
28
37
37
2
2
20
20
16
16
18
18
12
12
18
18
8
8
29
29
44
44
47
47
14
14
31
31
47
47
3
3
15
15
33
33
45
45
16
16
28
28
27
27
22
22
34
34
42
42
1
1
17
17
18
18
45
45
44
44
36
36
44
44
47
47
28
28
26
26
26
26
46
46
30
30
38
38
48
48
38
38
31
31
17
17
44
44
31
31
33
33
38
38
7
7
9
9
19
19
10
10
8
8
35
35
28
28
43
43
8
8
24
24
47
47
33
33
27
27
35
35
30
30
8
8
12
12
48
48
14
14
22
22
12
12
7
7
27
27
32
32
7
7
32
32

In [2]:
means = {
        "HOMEPAGE_BROWSE": 25,
        "PRODUCT_LIST": 35,
        "PRODUCT_DETAIL": 55,
        "ADD_TO_CART": 15,
        "VIEW_CART": 20,
        "PROCEED_CHECKOUT": 60,
        "PURCHASE": 15,
        "ABANDON": 5,
        "POST_PURCHASE_REVIEW": 120,
    }

In [5]:
means.get("ABANDONs", 10)

10

In [5]:
df = pd.read_clipboard(sep=',')

In [10]:
examples = df['Popular Examples (Global)'].copy()
# ['Payment Method',

In [12]:
examples.index = df['Payment Method'].values

In [20]:
payment_methods = {}
for xx in dict(examples).items():
    yy = xx[1].split(',')
    yy = [y.strip() for y in yy]
    payment_methods[xx[0]] = yy
    print(f"Payment Method: {xx[0]}")
    print(f"Examples: {yy}")

Payment Method: Digital Wallets (E-wallets)
Examples: ['PayPal', 'Apple Pay', 'Google Pay', 'Samsung Pay', 'Venmo', 'Alipay', 'WeChat Pay']
Payment Method: Credit & Debit Cards
Examples: ['Visa', 'Mastercard', 'American Express', 'Discover', 'Diners Club']
Payment Method: Buy Now, Pay Later (BNPL)
Examples: ['Klarna', 'Affirm', 'Afterpay', 'Sezzle', 'Zip']
Payment Method: Bank Transfers / ACH
Examples: ['ACH (USA)', 'SEPA (Europe)', 'Faster Payments (UK)']
Payment Method: Cryptocurrency
Examples: ['Bitcoin (BTC)', 'Ethereum (ETH)', 'USDT', 'USDC', 'Litecoin']
Payment Method: Cash on Delivery (COD)
Examples: ['Traditional COD (very common in emerging markets)']

In [21]:
payment_methods

{'Digital Wallets (E-wallets)': ['PayPal',
  'Apple Pay',
  'Google Pay',
  'Samsung Pay',
  'Venmo',
  'Alipay',
  'WeChat Pay'],
 'Credit & Debit Cards': ['Visa',
  'Mastercard',
  'American Express',
  'Discover',
  'Diners Club'],
 'Buy Now, Pay Later (BNPL)': ['Klarna',
  'Affirm',
  'Afterpay',
  'Sezzle',
  'Zip'],
 'Bank Transfers / ACH': ['ACH (USA)',
  'SEPA (Europe)',
  'Faster Payments (UK)'],
 'Cryptocurrency': ['Bitcoin (BTC)',
  'Ethereum (ETH)',
  'USDT',
  'USDC',
  'Litecoin'],
 'Cash on Delivery (COD)': ['Traditional COD (very common in emerging markets)']}

In [22]:
x = [{'a': 1, 'b': 2}, {'a': 3, 'b': 4}]

In [24]:
x.remove({'a': 1, 'b': 2})

In [26]:
def generate_ip():
    """
    That function can generate a total of 4,294,967,296 unique IP addresses
    """
    # Generates a random 32-bit integer and converts it to an IP string
    random_ip = ipaddress.IPv4Address(random.getrandbits(32))
    response = {"ip":str(random_ip)}
    return response

In [34]:
x = [4*2.5*6, 1*1.5*6 ,4*3*4 ]

In [35]:
sum(x)

117.0

In [41]:
x = df.values

In [47]:
x[:, 0].sum()

np.float64(1.0)

In [3]:
def generate_random_ip():
    # Generates a random 32-bit integer and converts it to an IP string
    random_ip = ipaddress.IPv4Address(random.getrandbits(32))
    return str(random_ip)

# Generate 5 sample IPs
samples = [generate_random_ip() for _ in range(5)]
for ip in samples:
    print(f"Sample IP: {ip}")

Sample IP: 39.156.179.226
Sample IP: 150.93.110.22
Sample IP: 79.211.254.185
Sample IP: 85.45.144.17
Sample IP: 173.168.217.244

In [10]:
generate_random_ip()

'129.147.82.33'

In [4]:
methods

['Digital Wallets (E-wallets)',
 'Credit & Debit Cards',
 'Buy Now, Pay Later (BNPL)',
 'Bank Transfers / ACH',
 'Cryptocurrency',
 'Cash on Delivery (COD)']